// Ubigeo del Perú: Departamentos, Provincias y Distritos principales
export const UBIGEO_PERU = {
  "AMAZONAS": {
    "CHACHAPOYAS": ["CHACHAPOYAS", "ASUNCION", "BALSAS", "CHETO", "CHILIQUIN", "CHUQUIBAMBA", "LEIMEBAMBA", "LEVANTO", "MAGDALENA", "MARISCAL CASTILLA", "MOLINOPAMPA", "MONTEVIDEO", "OLLEROS", "QUINJALCA", "SAN FRANCISCO DE DAGUAS", "SAN ISIDRO DE MAINO", "SOLOCO", "SONCHE"],
    "BAGUA": ["BAGUA", "ARAMANGO", "COPALLIN", "EL PARCO", "IMAZA", "LA PECA"],
    "BONGARA": ["JUMBILLA", "CHISQUILLA", "CHURUJA", "COROSHA", "CUPESNICO", "FLORIDA", "JAZAN", "RECTA", "SAN CARLOS", "SHIPASBAMBA", "VALERA", "YAMBRASBAMBA"],
    "CONDORCANQUI": ["NIEVA", "EL CENEPA", "RIO SANTIAGO"],
    "LUYA": ["LAMUD", "CAMPORREDONDO", "COCABAMBA", "COCHAMAL", "CONILA", "INGUILPATA", "LONGUITA", "LONYA CHICO", "LUYA", "LUYA VIEJO", "MARIA", "OCALLI", "OCUMAL", "PISUQUIA", "PROVIDENCIA", "SAN CRISTOBAL", "SAN FRANCISCO DEL YESO", "SAN JERONIMO", "SAN JUAN DE LOPECANALES", "SANTA CATALINA", "SANTO TOMAS", "TINGO", "TRITA"],
    "RODRIGUEZ DE MENDOZA": ["SAN NICOLAS", "CHURUJA", "COCHAMAL", "HUAMBO", "LIMABAMBA", "LONGAR", "MARISCAL BENAVIDES", "MILPUC", "OMIA", "SANTA ROSA", "TOTORA", "VISTA ALEGRE"],
    "UTCUBAMBA": ["BAGUA GRANDE", "CAJARURO", "CUMBA", "EL MILAGRO", "JAMALCA", "LONYA GRANDE", "YAMON"]
  },
  "ANCASH": {
    "SANTA": ["CHIMBOTE", "NUEVO CHIMBOTE", "COISHCO", "SANTA", "NEPEÑA", "CACERES DEL PERU", "MORO", "SAMANCO", "MACATE"],
    "HUARAZ": ["HUARAZ", "INDEPENDENCIA", "COCHABAMBA", "COLCABAMBA", "JANGAS", "LA LIBERTAD", "OLLEROS", "PAMPAS", "PARIACOTO", "PIRA", "TARICA"],
    "CASMA": ["CASMA", "BUENA VISTA ALTA", "COMANDANTE NOEL", "YAUTAN"],
    "HUARMEY": ["HUARMEY", "COCHAPETI", "CULEBRAS", "HUAYAN", "MALVAS"],
    "CARHUAZ": ["CARHUAZ", "ACOPAMPA", "AMASHCA", "ANTA", "ATAQUERO", "MARCARA", "PARIAHUANCA", "SAN MIGUEL DE ACO", "SHILLA", "TINCO", "YUNGAR"],
    "HUAYLAS": ["CARAZ", "HUATA", "HUAYLAS", "MATO", "PAMPAROMAS", "PUEBLO LIBRE", "SANTA CRUZ", "SANTO TORIBIO", "YURACMARCA"],
    "YUNGAY": ["YUNGAY", "CASHAPAMPA", "MANCOS", "MATACOTO", "QUILLO", "RANRAHIRCA", "SHUPLUY", "YANAMA"],
    "HUARI": ["HUARI", "ANRA", "CAJAY", "CHAVIN DE HUANTAR", "HUACACHI", "HUACCHIS", "HUACHIS", "HUANTAR", "MASIN", "PAUCAS", "PONTO", "RAHUAPAMPA", "RAPAYAN", "SAN MARCOS", "SAN PEDRO DE CHANA", "UCO"],
    "RECUAY": ["RECUAY", "CATAC", "COTAPARACO", "HUAYLLAPAMPA", "LLACLLIN", "MARCA", "PAMPAS CHICO", "PARARIN", "TAPACOCHA", "TICAPAMPA"]
  },
  "AREQUIPA": {
    "AREQUIPA": ["AREQUIPA", "ALTO SELVA ALEGRE", "CAYMA", "CERRO COLORADO", "CHARACATO", "CHIGUATA", "JACOBO HUNTER", "LA JOYA", "MARIANO MELGAR", "MIRAFLORES", "MOLLEBAMBA", "PAUCARPATA", "POCSI", "POLOBAYA", "QUEQUEÑA", "SABANDIA", "SACHACA", "SAN JUAN DE SIGUAS", "SAN JUAN DE TARUCANI", "SANTA ISABEL DE SIGUAS", "SANTA RITA DE SIGUAS", "SOCABAYA", "TIABAYA", "UCHUMAYO", "VITOR", "YANAHUARA", "YARABAMBA", "YURA"],
    "CAMANA": ["CAMANA", "JOSE MARIA QUIMPER", "MARIANO NICOLAS VALCARCEL", "MARISCAL CACERES", "NICOLAS DE PIEROLA", "OCONA", "QUILCA", "SAMUEL PASTOR"],
    "CARAVELI": ["CARAVELI", "ACARI", "ATICO", "ATIQUIPA", "BELLA UNION", "CAHUACHO", "CHALA", "CHAPARRA", "HUANUHUANU", "JAQUI", "LOMAS", "QUICACHA", "YAUCA"],
    "CASTILLA": ["APLAO", "ANDAGUA", "AYO", "CHACHAS", "CHILCAYMARCA", "CHOCO", "HUANCARQUI", "MACHAGUAY", "ORCOPAMPA", "PAMPACOLCA", "TIPAN", "UÑON", "URACA", "VIRACO"],
    "CAYLLOMA": ["CHIVAY", "ACHOMA", "CABANACONDE", "CALLALLI", "CAYLLOMA", "COPORAQUE", "HUAMBO", "HUANCA", "LLUTA", "MACA", "MADRIGAL", "MAJES", "SAN ANTONIO DE CHUCA", "SIBAYO", "TAPAY", "TISCO", "TUTI", "YANQUE"],
    "ISLAY": ["MOLLENDO", "COCACHACRA", "DEAN VALDIVIA", "ISLAY", "MEJIA", "PUNTA DEBOMBON"],
    "CONDESUYOS": ["CHUQUIBAMBA", "ANDARAY", "CAYARANI", "CHICHAS", "IRAY", "RIO GRANDE", "SALAMANCA", "YANAQUIHUA"]
  },
  "LA LIBERTAD": {
    "TRUJILLO": ["TRUJILLO", "EL PORVENIR", "FLORENCIA DE MORA", "HUANCHACO", "LA ESPERANZA", "LAREDO", "MOCHE", "POROTO", "SALAVERRY", "SIMBAL", "VICTOR LARCO HERRERA"],
    "ASCOPE": ["ASCOPE", "CHICAMA", "CHOCOPE", "MAGDALENA DE CAO", "PAIJAN", "RAZURI", "SANTIAGO DE CAO", "CASA GRANDE"],
    "CHEPEN": ["CHEPEN", "PACANGA", "PUEBLO NUEVO"],
    "PACASMAYO": ["SAN PEDRO DE LLOC", "GUADALUPE", "JEQUETEPEQUE", "PACASMAYO", "SAN JOSE"],
    "VIRU": ["VIRU", "CHAO", "GUADALUPITO"],
    "SANCHEZ CARRION": ["HUAMACHUCO", "CHUGAY", "COCHORCO", "CURGOS", "MARCABAL", "SANAGORAN", "SARIN", "SITABAMBA"],
    "OTUZCO": ["OTUZCO", "AGALLPAMPA", "CHARAT", "HUANGAMARCA", "LA CUESTA", "MACHE", "PARANDAY", "SALPO", "SIVINCHA", "USQUIL"]
  },
  "LIMA": {
    "LIMA": ["LIMA", "ANCON", "ATE", "BARRANCO", "BREÑA", "CARABAYLLO", "CHACLACAYO", "CHORRILLOS", "CIENEGUILLA", "COMAS", "EL AGUSTINO", "INDEPENDENCIA", "JESUS MARIA", "LA MOLINA", "LA VICTORIA", "LINCE", "LOS OLIVOS", "LURIGANCHO", "LURIN", "MAGDALENA DEL MAR", "MIRAFLORES", "PACHACAMAC", "PUCOUSANA", "PUEBLO LIBRE", "PUENTE PIEDRA", "PUNTA HERMOSA", "PUNTA NEGRA", "RIMAC", "SAN BARTOLO", "SAN BORJA", "SAN ISIDRO", "SAN JUAN DE LURIGANCHO", "SAN JUAN DE MIRAFLORES", "SAN LUIS", "SAN MARTIN DE PORRES", "SAN MIGUEL", "SANTA ANITA", "SANTA MARIA DEL MAR", "SANTA ROSA", "SANTIAGO DE SURCO", "SURQUILLO", "VILLA EL SALVADOR", "VILLA MARIA DEL TRIUNFO"],
    "BARRANCA": ["BARRANCA", "PARAMONGA", "PATIVILCA", "SUPE", "SUPE PUERTO"],
    "CAÑETE": ["SAN VICENTE DE CAÑETE", "ASIA", "CALANGO", "CERRO AZUL", "CHILCA", "COAYLLO", "IMPERIAL", "LUNAHUANA", "MALALA", "PACARAN", "SAN ANTONIO", "SAN LUIS", "SANTA CRUZ DE FLORES", "ZUNIGA"],
    "HUARAL": ["HUARAL", "ATAVILLOS ALTO", "ATAVILLOS BAJO", "AUCALLAMA", "CHANCAY", "IHVARI", "LAMPIAN", "PACARAOS", "SANTA CRUZ DE ANDAMARCA", "SUMBILCA", "VEINTISEIS DE NOVIEMBRE"],
    "HUAURA": ["HUACHO", "AMBAR", "CALETA DE CARQUIN", "CHECRAS", "HUALMAY", "HUAURA", "LEONCIO PRADO", "PACCHO", "SANTA LEONOR", "SANTA MARIA", "SAYAN", "VEGUETA"]
  },
  "PIURA": {
    "PIURA": ["PIURA", "CASTILLA", "CATACAOS", "CURA MORI", "EL TALLAN", "LA ARENA", "LA UNION", "LAS LOMAS", "TAMBO GRANDE", "26 DE OCTUBRE"],
    "TALARA": ["PARIÑAS", "EL ALTO", "LA BREA", "LOBITOS", "MANCORA", "ORGANOS"],
    "SULLANA": ["SULLANA", "BELLAVISTA", "IGNACIO ESCUDERO", "LANCONES", "MARCAVELICA", "MIGUEL CHECA", "QUERECOTILLO", "SALITRAL"],
    "PAITA": ["PAITA", "AMOTAPE", "COLAN", "EL ARENAL", "LA HUACA", "TAMARINDO", "VICHAYAL"],
    "SECHURA": ["SECHURA", "BELLAVISTA DE LA UNION", "BERNAL", "CRISTO NOS VALGA", "RINCONADA LLICUAR", "VICE"]
  }
};

export const LISTA_DEPARTAMENTOS_PERU = Object.keys(UBIGEO_PERU).concat([
  "APURIMAC", "AYACUCHO", "CAJAMARCA", "CALLAO", "CUSCO", "HUANCAVELICA", "HUANUCO", "ICA", "JUNIN", "LAMBAYEQUE", "LORETO", "MADRE DE DIOS", "MOQUEGUA", "PASCO", "PUNO", "SAN MARTIN", "TACNA", "TUMBES", "UCAYALI"
]).filter((v, i, a) => a.indexOf(v) === i).sort();
